Http/routes.php
<?php

use Illuminate\Support\Facades\Route;

$prefix = \Config::get('lfm.prefix', 'FileManager');

$namespace = '\Mediapress\FileManager\Http\Controllers';
Route::group(['prefix' => $prefix, 'as' => 'admin.filemanager.', 'namespace' => $namespace], function () {

    Route::get('/image/{path}', [
        'uses' => 'LfmController@image',
        'as' => 'image'
    ]);

    // Show LFM
    Route::get('/', [
        'uses' => 'LfmController@show',
        'as' => 'show'
    ]);

    // upload
    Route::any('/upload', [
        'uses' => 'UploadController@upload',
        'as' => 'upload'
    ]);

    // list images & files
    Route::get('/jsonitems', [
        'uses' => 'ItemsController@getItems',
        'as' => 'getItems'
    ]);

    // folders
    Route::get('/newfolder', [
        'uses' => 'FolderController@getAddfolder',
        'as' => 'getAddfolder'
    ]);
    Route::get('/deletefolder', [
        'uses' => 'FolderController@getDeletefolder',
        'as' => 'getDeletefolder'
    ]);
    Route::get('/folders', [
        'uses' => 'FolderController@getFolders',
        'as' => 'getFolders'
    ]);

    // crop
    Route::get('/crop', [
        'uses' => 'CropController@getCrop',
        'as' => 'getCrop'
    ]);
    Route::get('/cropimage', [
        'uses' => 'CropController@getCropimage',
        'as' => 'getCropimage'
    ]);

    // rename
    Route::get('/rename', [
        'uses' => 'RenameController@getRename',
        'as' => 'getRename'
    ]);

    // scale/resize
    Route::get('/resize', [
        'uses' => 'ResizeController@getResize',
        'as' => 'getResize'
    ]);
    Route::get('/doresize', [
        'uses' => 'ResizeController@performResize',
        'as' => 'performResize'
    ]);

    // download
    Route::get('/download', [
        'uses' => 'DownloadController@getDownload',
        'as' => 'getDownload'
    ]);

    // delete
    Route::get('/delete', [
        'uses' => 'DeleteController@getDelete',
        'as' => 'getDelete'
    ]);

    Route::get('/demo', function () {
        return view('filemanager::demo');
    });
});

Resources/views/crop.blade.php
<div class="row fill">
  <div class="col-md-8 fill">
    <div class="crop-container">
      <img src="{{ asset($img) }}" class="img img-responsive">
    </div>
  </div>
  <div class="col-md-4 fill">
    <div class="text-center">

      <div class="img-preview center-block"></div>
      <br>
      <button class="btn btn-primary" onclick="performCrop()">{{ trans('filemanager::lfm.btn-crop') }}</button>
      <button class="btn btn-info" onclick="loadItems()">{{ trans('filemanager::lfm.btn-cancel') }}</button>
      <form action="{{ route('admin.filemanager.getCrop') }}" role='form' name='cropForm' id='cropForm' mathod='post'>
        <input type="hidden" id="img" name="img" value="{{ $img }}">
        <input type="hidden" id="working_dir" name="working_dir" value="{{ $working_dir }}">
        <input type="hidden" id="dataX" name="dataX">
        <input type="hidden" id="dataY" name="dataY">
        <input type="hidden" id="dataWidth" name="dataWidth">
        <input type="hidden" id="dataHeight" name="dataHeight">
        <input type='hidden' name='_token' value='{{csrf_token()}}'>
      </form>
    </div>
  </div>

</div>

<script>
  $(document).ready(function () {
    var $dataX = $('#dataX'),
    $dataY = $('#dataY'),
    $dataHeight = $('#dataHeight'),
    $dataWidth = $('#dataWidth');
    $('.crop-container > img').cropper({
      //aspectRatio: 16 / 9,
      preview: ".img-preview",
      strict: false,
      crop: function (data) {
        // Output the result data for cropping image.
        $dataX.val(Math.round(data.x));
        $dataY.val(Math.round(data.y));
        $dataHeight.val(Math.round(data.height));
        $dataWidth.val(Math.round(data.width));
      }
    });
  });
  function performCrop() {
    $.ajax({
      type: "GET",
      dataType: "text",
      url: "{{ route('admin.filemanager.getCropimage') }}",
      data: {
        img: '{{ $img }}',
        working_dir: $("#working_dir").val(),
        dataX: $("#dataX").val(),
        dataY: $("#dataY").val(),
        dataHeight: $("#dataHeight").val(),
        dataWidth: $("#dataWidth").val(),
        type: $('#type').val()
      },
      cache: false
    }).done(function (data) {
      loadItems();
    });
  }
</script>

Resources/views/demo.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Laravel Filemanager</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <div class="container">
    <h1 class="page-header">Integration Demo Page</h1>
    <div class="row">
      <div class="col-md-6">
        <h2>CKEditor</h2>
        <textarea name="ce" class="form-control"></textarea>
      </div>
      <div class="col-md-6">
        <h2>TinyMCE</h2>
        <textarea name="tm" class="form-control"></textarea>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h2>Independent usage</h2>
        <div class="input-group">
          <span class="input-group-btn">
            <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
              <i class="fa fa-picture-o"></i> Choose
            </a>
          </span>
          <input id="thumbnail" class="form-control" type="text" name="filepath">
        </div>
        <img id="holder" style="margin-top:15px;max-height:100px;">
      </div>
    </div>
  </div>

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <!-- CKEditor init -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.11/ckeditor.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.11/adapters/jquery.js"></script>
  <script>
    $('textarea[name=ce]').ckeditor({
      height: 100,
      filebrowserImageBrowseUrl: '/file-manager?type=Images',
      filebrowserImageUploadUrl: '/file-manager/upload?type=Images&_token={{csrf_token()}}',
      filebrowserBrowseUrl: '/file-manager?type=Files',
      filebrowserUploadUrl: '/file-manager/upload?type=Files&_token={{csrf_token()}}'
    });
  </script>

  <!-- TinyMCE init -->
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>
    var editor_config = {
      path_absolute : "/",
      selector: "textarea[name=tm]",
      plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
      relative_urls: false,
      file_browser_callback : function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

        var cmsURL = editor_config.path_absolute + 'file-manager?field_name=' + field_name;
        if (type == 'image') {
          cmsURL = cmsURL + "&type=Images";
        } else {
          cmsURL = cmsURL + "&type=Files";
        }

        tinyMCE.activeEditor.windowManager.open({
          file : cmsURL,
          title : 'Filemanager',
          width : x * 0.8,
          height : y * 0.8,
          resizable : "yes",
          close_previous : "no"
        });
      }
    };

    tinymce.init(editor_config);
  </script>

  <script src="/vendor/file-manager/js/lfm.js"></script>
  <script>
    $('#lfm').filemanager('image');
  </script>
</body>
</html>

Resources/views/folders.blade.php
<div class="col-sm-4 col-md-3 col-lg-2">
    <div class="thumbnail text-center" data-id="{{ $dir_name['long'] }}">
        <a data-id="{{ $dir_name['long'] }}" class="folder-icon pointer folder-item">
            <img src="{{ asset('vendor/FileManager/img/folder.png') }}" style='max-height:200px;'>
        </a>
    </div>
    <div class="caption text-center">
        <div class="btn-group">
            <button type="button" data-id="{{ $dir_name['long'] }}" class="btn btn-default btn-xs folder-item">
                {{ str_limit($dir_name['short'], $limit = 10, $end = '...') }}
            </button>
            <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown"
                    aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                @if(Config::get("lfm.folder_rename"))
                    <li><a href="javascript:rename('{{ $dir_name['short'] }}')"><i
                                    class="fa fa-edit fa-fw"></i> {{ trans('filemanager::lfm.menu-rename') }}</a></li>
                @endif
                <li><a href="javascript:trash('{{ $dir_name['short'] }}')"><i
                                class="fa fa-trash fa-fw"></i> {{ trans('filemanager::lfm.menu-delete') }}</a></li>
            </ul>
        </div>

    </div>
</div>

Resources/views/grid-view.blade.php
<div class="row">

    @if((sizeof($file_info) > 0) || (sizeof($directories) > 0))

        @foreach($directories as $key => $dir_name)
            @include('filemanager::folders')
        @endforeach

        @foreach($file_info as $key => $file)
            @include('filemanager::item')
        @endforeach

    @else
        <div class="col-md-12">
            <p>{{ trans('filemanager::lfm.message-empty') }}</p>
        </div>
    @endif

</div>

Resources/views/image.blade.php
<div class="modal-body">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    <img src="{{$src}}" alt="" />
</div>
<style>
    .modal-body img{
        max-width: 100%;
    }
    .modal-body,.modal-header{
       padding: 0;
    }
    .modal-body button{
        position: absolute;
        right: -40px;
        top: 0px;
        color: white;
        padding: 10px 14px;
        background: black;
        opacity: 1;
    }
</style>

Resources/views/index.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ trans('filemanager::lfm.title-page') }}</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{ asset('vendor/FileManager/css/cropper.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/vendor/FileManager/css/lfm.css') }}">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
</head>
<body>
  <div class="container">
    <div class="row fill">
      <div class="panel panel-primary fill">
        <div class="panel-heading">
          <h3 class="panel-title">{{ trans('filemanager::lfm.title-panel') }}</h3>
        </div>
        <div class="panel-body fill">
          <div class="row fill">
            <div class="wrapper fill">
              <div class="col-md-2 col-lg-2 col-sm-2 col-xs-2 left-nav fill" id="lfm-leftcol">
                <div id="tree1">
                </div>
              </div>
              <div class="col-md-10 col-lg-10 col-sm-10 col-xs-10 right-nav" id="right-nav">
                <div class="row">
                  <div class="col-md-12">
                    @if($extension_not_found)
                    <div class="alert alert-warning"><i class="glyphicon glyphicon-exclamation-sign"></i> {{ trans('filemanager::lfm.message-extension_not_found') }}</div>
                    @endif
                    <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>
                        <div class="collapse navbar-collapse">
                          <ul class="nav navbar-nav" id="nav-buttons">
                            <li>
                              <a href="#" id="to-previous">
                                <i class="fa fa-arrow-left"></i> {{ trans('filemanager::lfm.nav-back') }}
                              </a>
                            </li>
                            <li><a style='cursor:default;'>|</a></li>
                            <li>
                              <a href="#" id="add-folder">
                                <i class="fa fa-plus"></i> {{ trans('filemanager::lfm.nav-new') }}
                              </a>
                            </li>
                            <li>
                              <a href="#" id="upload" data-toggle="modal" data-target="#uploadModal">
                                <i class="fa fa-upload"></i> {{ trans('filemanager::lfm.nav-upload') }}
                              </a>
                            </li>
                            <li><a style='cursor:default;'>|</a></li>
                            <li>
                              <a href="#" id="thumbnail-display">
                                <i class="fa fa-picture-o"></i> {{ trans('filemanager::lfm.nav-thumbnails') }}
                              </a>
                            </li>
                            <li>
                              <a href="#" id="list-display">
                                <i class="fa fa-list"></i> {{ trans('filemanager::lfm.nav-list') }}
                              </a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </nav>
                  </div>
                </div>

                @if (isset($errors) && $errors->any())
                <div class="row">
                  <div class="col-md-12">
                    <div class="alert alert-danger" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <ul>
                        @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                      </ul>
                    </div>
                  </div>
                </div>
                @endif

                <div id="content" class="fill">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aia-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">{{ trans('filemanager::lfm.title-upload') }}</h4>
        </div>
        <div class="modal-body">
          <form action="{{ route('admin.filemanager.upload') }}" role='form' id='uploadForm' name='uploadForm' method='post' enctype='multipart/form-data'>
            <div class="form-group" id="attachment">
              <label for='upload' class='control-label'>{{ trans('filemanager::lfm.message-choose') }}</label>
              <div class="controls">
                <div class="input-group" style="width: 100%">
                  <input type="file" id="upload" name="upload">
                </div>
              </div>
            </div>
            <input type='hidden' name='working_dir' id='working_dir' value='{{$working_dir}}'>
            <input type='hidden' name='show_list' id='show_list' value='0'>
            <input type='hidden' name='type' id='type' value='{{$file_type}}'>
            <input type='hidden' name='_token' value='{{csrf_token()}}'>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('filemanager::lfm.btn-close') }}</button>
          <button type="button" class="btn btn-primary" id="upload-btn">{{ trans('filemanager::lfm.btn-upload') }}</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="fileViewModal" tabindex="-1" role="dialog" aria-labelledby="fileLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="fileLabel">{{ trans('filemanager::lfm.title-view') }}</h4>
        </div>
        <div class="modal-body" id="fileview_body">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('filemanager::lfm.btn-close') }}</button>
        </div>
      </div>
    </div>
  </div>

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.4.0/jquery-migrate.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.3.0/bootbox.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  <script src="{{ asset('vendor/FileManager/js/cropper.min.js') }}"></script>
  <script src="{{ asset('vendor/FileManager/js/jquery.form.min.js') }}"></script>
  @include('filemanager::script')
</body>
</html>

Resources/views/item.blade.php
<?php $file_name = $file_info[$key]['name'];?>
@if($type == 'Images')
    <?php $thumb_src = $thumb_url . $file_name;?>
@endif

<div class="col-sm-4 col-md-3 col-lg-2 img-row">

    <div class="thumbnail thumbnail-img text-center" data-id="{{ $file_name }}" id="img_thumbnail_{{ $key }}">
        @if($type == 'Images')
            <img id="{{ $file_name }}" src="{{ asset($thumb_src) }}" alt="{{$file_name}}" class="pointer"
                 onclick="useFile({{ "'".$file_name."',".$file_info[$key]["id"]}})">
        @else
            <i class="fa {{ $file['icon'] }} fa-5x" style="height:200px;cursor:pointer;padding-top:60px;"
               onclick="useFile('{{ $file_name }}')"></i>
        @endif
    </div>

    <div class="caption text-center">
        <div class="btn-group">
            <button type="button" onclick="useFile({{ "'".$file_name."',".$file_info[$key]["id"]}})"
                    class="btn btn-default btn-xs">
                {{ str_limit($file_name, $limit = 10, $end = '...') }}
            </button>
            <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown"
                    aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:rename('{{ $file_name }}')"><i
                                class="fa fa-edit fa-fw"></i> {{ trans('filemanager::lfm.menu-rename') }}</a></li>
                <li><a href="javascript:download('{{ $file_name }}')"><i
                                class="fa fa-download fa-fw"></i> {{ trans('filemanager::lfm.menu-download') }}</a></li>
                <li class="divider"></li>
                @if($type == 'Images')
                    <li><a href="javascript:fileView('{{ $file_name }}')"><i
                                    class="fa fa-image fa-fw"></i> {{ trans('filemanager::lfm.menu-view') }}</a></li>
                    {{--<li><a href="javascript:notImp()">Rotate</a></li>--}}
                    <li><a href="javascript:resizeImage('{{ $file_name }}')"><i
                                    class="fa fa-arrows fa-fw"></i> {{ trans('filemanager::lfm.menu-resize') }}</a></li>
                    <li><a href="javascript:cropImage('{{ $file_name }}')"><i
                                    class="fa fa-crop fa-fw"></i> {{ trans('filemanager::lfm.menu-crop') }}</a></li>
                    <li class="divider"></li>
                @endif
                <li><a href="javascript:trash('{{ $file_name }}')"><i
                                class="fa fa-trash fa-fw"></i> {{ trans('filemanager::lfm.menu-delete') }}</a></li>
            </ul>
        </div>
    </div>
</div>

Resources/views/list-view.blade.php
@if((sizeof($file_info) > 0) || (sizeof($directories) > 0))
<table class="table table-condensed table-striped">
  <thead>
    <th style='width:50%;'>{{ trans('filemanager::lfm.title-item') }}</th>
    <th>{{ trans('filemanager::lfm.title-size') }}</th>
    <th>{{ trans('filemanager::lfm.title-type') }}</th>
    <th>{{ trans('filemanager::lfm.title-modified') }}</th>
    <th>{{ trans('filemanager::lfm.title-action') }}</th>
  </thead>
  <tbody>
    @foreach($directories as $key => $dir_name)
    <tr>
      <td>
        <i class="fa fa-folder-o"></i>
        <a class="folder-item pointer" data-id="{{ $dir_name['long'] }}">
          {{ $dir_name['short'] }}
        </a>
      </td>
      <td></td>
      <td>{{ trans('filemanager::lfm.type-folder') }}</td>
      <td></td>
      <td></td>
    </tr>
    @endforeach

    @foreach($file_info as $file)
    <tr>
      <td>
        @if($type == 'Images')
        <i class="fa fa-image"></i>
        @else
        <i class="fa {{ $file['icon'] }}"></i>
        @endif
        <?php $file_name = $file['name'];?>
        <a href="javascript:useFile({{ "'".$file_name."',".$file_info[$key]["id"]}})">
          {{ $file_name }}
        </a>
        &nbsp;&nbsp;
        <a href="javascript:rename('{{ $file_name }}')">
          <i class="fa fa-edit"></i>
        </a>
      </td>
      <td>
        {{ $file['size'] }}
      </td>
      <td>
        {{ $file['type'] }}
      </td>
      <td>
        {{ date("Y-m-d h:m", $file['created']) }}
      </td>
      <td>
        <a href="javascript:trash('{{ $file_name }}')">
          <i class="fa fa-trash fa-fw"></i>
        </a>
        @if($type == 'Images')
        <a href="javascript:cropImage('{{ $file_name }}')">
          <i class="fa fa-crop fa-fw"></i>
        </a>
        <a href="javascript:resizeImage('{{ $file_name }}')">
          <i class="fa fa-arrows fa-fw"></i>
        </a>
        {{--<a href="javascript:notImp()">--}}
        {{--<i class="fa fa-rotate-left fa-fw"></i>--}}
        {{--</a>--}}
        @endif
      </td>
    </tr>
    @endforeach
  </tbody>
</table>

@else
<div class="row">
  <div class="col-md-12">
    <p>{{ trans('filemanager::lfm.message-empty') }}</p>
  </div>
</div>
@endif

Resources/views/resize.blade.php
<div class="container">
  <div class="row fill">
    <div class="col-md-8 fill" id="containment">
      <img id="resize" src="{{ asset($img) }}" height="{{ $height }}" width="{{ $width }}">
    </div>
    <div class="col-md-4 fill">

      <table class="table table-compact table-striped">
        <thead></thead>
        <tbody>
          @if ($scaled)
          <tr>
            <td>{{ trans('filemanager::lfm.resize-ratio') }}</td>
            <td>{{ number_format($ratio, 2) }}</td>
          </tr>
          <tr>
            <td>{{ trans('filemanager::lfm.resize-scaled') }}</td>
            <td>
              {{ trans('filemanager::lfm.resize-true') }}
            </td>
          </tr>
          @endif
          <tr>
            <td>{{ trans('filemanager::lfm.resize-old-height') }}</td>
            <td>{{ $original_height }}px</td>
          </tr>
          <tr>
            <td>{{ trans('filemanager::lfm.resize-old-width') }}</td>
            <td>{{ $original_width }}px</td>
          </tr>
          <tr>
            <td>{{ trans('filemanager::lfm.resize-new-height') }}</td>
            <td><span id="height_display"></span></td>
          </tr>
          <tr>
            <td>{{ trans('filemanager::lfm.resize-new-width') }}</td>
            <td><span id="width_display"></span></td>
          </tr>
        </tbody>
      </table>

      <button class="btn btn-primary" onclick="doResize()">{{ trans('filemanager::lfm.btn-resize') }}</button>
      <button class="btn btn-info" onclick="loadItems()">{{ trans('filemanager::lfm.btn-cancel') }}</button>

      <input type="hidden" name="ratio" value="{{ $ratio }}"><br>
      <input type="hidden" name="scaled" value="{{ $scaled }}"><br>
      <input type="hidden" id="original_height" name="original_height" value="{{ $original_height }}"><br>
      <input type="hidden" id="original_width" name="original_width" value="{{ $original_width }}"><br>
      <input type="hidden" id="height" name="height" value=""><br>
      <input type="hidden" id="width" name="width">

    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    $("#height_display").html($("#resize").height() + "px");
    $("#width_display").html($("#resize").width() + "px");

    $("#resize").resizable({
      aspectRatio: true,
      containment: "#containment",
      handles: "n, e, s, w, se, sw, ne, nw",
      resize: function (event, ui) {
        $("#width").val($("#resize").width());
        $("#height").val($("#resize").height());
        $("#height_display").html($("#resize").height() + "px");
        $("#width_display").html($("#resize").width() + "px");
      }
    });
  });

  function doResize() {
    $.ajax({
      type: "GET",
      dataType: "text",
      url: "{{ route('admin.filemanager.performResize') }}",
      data: {
        img: '{{ $img }}',
        working_dir: $("#working_dir").val(),
        dataX: $("#dataX").val(),
        dataY: $("#dataY").val(),
        dataHeight: $("#height").val(),
        dataWidth: $("#width").val()
      },
      cache: false
    }).done(function (data) {
      if (data == "OK") {
        loadItems();
      } else {
        notify(data);
      }
    });
  }
</script>

Resources/views/tree.blade.php
<ul class="list-unstyled">
  @if(Config::get('lfm.allow_multi_user'))
  <li style="margin-left: -10px;">
    <a class="pointer folder-item" data-id="{{ $user_dir }}">
      <i class="fa fa-folder-open"></i> {{ trans('filemanager::lfm.title-root') }}
    </a>
  </li>
  @foreach($dirs as $key => $dir_name)
  <li>
    <a class="pointer folder-item" data-id="{{ $dir_name['long'] }}">
      <i class="fa fa-folder"></i> {{ $dir_name['short'] }}
    </a>
  </li>
  @endforeach
  <hr>
  @endif
  <li style="margin-left: -10px;">
    <a class="pointer folder-item" data-id="{{ $share_dir }}">
      <i class="fa fa-folder"></i> {{ trans('filemanager::lfm.title-shares') }}
    </a>
  </li>
  @foreach($shares as $key => $dir_name)
  <li>
    <a class="pointer folder-item" data-id="{{ $dir_name['long'] }}">
      <i class="fa fa-folder"></i> {{ $dir_name['short'] }}
    </a>
  </li>
  @endforeach
</ul>